name: test
on: push
jobs:
  StoryBook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Prepare config
        run: cp contrib/emr-config/config.local.js contrib/emr-config/config.js
      - name: Install deps
        run: yarn install
      - run: yarn extract
      - run: yarn compile
      - name: Install Playwright
        run: yarn playwright install --with-deps chromium
      - name: Test storybook
        run: yarn test-storybook --run
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Prepare config
        run: cp contrib/emr-config/config.local.js contrib/emr-config/config.js
      - name: Install deps
        run: yarn install
      - run: yarn extract
      - run: yarn compile
      - name: Build package
        run: yarn build:lib
      - name: Check types
        run: yarn typecheck
      - name: Check eslint
        run: yarn eslint src/
      - name: Check formatting
        run: yarn prettier -c "src/**/*.ts?"
      - name: Run tests
        run: yarn test --run --silent
